spring:
  datasource:
    url: jdbc:mysql://45.118.145.149:3306/billingdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update